---
title: "Reliability"
author: "Margaret Wu"
date: "16 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
This document shows how test reliability is affected by test length, sample size and the range of student abilities.

```{r, echo=FALSE, message = FALSE}
rm(list = ls())  #remove all variables in memory
library(CTT)
library(knitr)

Rel <- rep(0,10)
TestLength <- seq(10,100,length=10)
for (i in 1:10){
# Generate dichotomous Rasch item responses
set.seed(6778)
N <- 2000           # number of students
theta <- rnorm( N ) # student abilities
I <-TestLength[i]            # number of items
p1 <- plogis( outer( theta , seq( -2 , 2 , len=I ) , "-" ) )  #item difficulties from -2 to 2
resp <- 1 * ( p1 > matrix( runif( N*I ) , nrow=N , ncol=I ) )  # item responses
colnames(resp) <- paste("I" , 1:I, sep="")

#Run item analysis
CTTstats <- CTT::reliability(resp)
Rel[i] <- CTTstats$alpha
}
```

## Reliability as a function of test length

```{r, echo=FALSE}
res <- data.frame(TestLength,round(Rel,2))
kable(res,col.names=c("Test Length","Test Reliability"),align='cc')

```

## A plot of test reliability as a function of test length
```{r, echo=FALSE}
plot(TestLength, round(Rel,2))
```


