---
title: "Anotações"
author: "Ana Crispim"
format: html
editor: visual
---

## Anotações - Grupo de estudos sobre TRI

-   Google meet: https://meet.google.com/azy-yrzw-wkb

## 27 de março de 2024

### Leituras

-   Ler mais sobre Templin (2016)

## 17 de abril de 2024

### Leituras

-   Ler conceitos básicos sobre psicometria

-   Ler Coltmean et al 2009 Formative versus reflective measurement models two applications

-   A more nuanced view of reliability

-   Embretson arbitrary metrics American Psychologist

-   Educational measurement for applied researchers

    -   TAM (modelo PISA)

### Anotações

-   Na TCT, o lambda (discriminação) é tido como constante para todos os itens

-   Na TRI, o lambda pode variar a depender do número de parâmetros estimados.

    -   É um modelo reflexivo e entende-se que o theta causa "o comportamento" por meio das variáveis fantasmas (y\* ...) e observadas (y ...). A variável fantasma é o que contém os thresholds.

        -   O acerto é causado pelo theta e pela dificuldade

-   Um teste precisa ser confiável (precisão), útil (validade), stable frame of reference (invariância) e com sentido substantivo

    -   No modelo de 1PL, o x que o e é elevado à representa a escala theta de habilidade (theta\[habilidade do sujeito\] - delta\[dificuldade do item\])

        -   Pra ser positivo, o theta tem que superar o delta

        -   A TRI propõe um link entre habilidade e dificuldade

            -   Pessoas mais hábeis tem maiores chances de responderem itens mais difíceis e fáceis

            -   Pessoas menos hábeis tem menores chances de responderem mais difíceis e maiores chances de responderem itens mais fáceis, a depender do theta (habilidade)

            -   Itens com mais informação são os itens com maior variância (mais pessoas respondendo em vários níveis de habilidade)

## Referências

Templin J. L., Henson R. A. (2006). Measurement of psychological disorders using cognitive diagnosis models. *Psychological Methods*, 11(3), 287--305. doi:10.1037/1082-989X.11.3.287
